source 'https://rubygems.org'

gem 'bcrypt', require: 'bcrypt'
gem 'jquery-rails'
gem 'rails', '3.2.14'
gem 'rubocop'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
